version: "3"

services:
    client_db:
        image: postgres:11
        container_name: card_db
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=card_db